/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "asd.check" instead.
 */

#include <check.h>
#include <math.h>

#include "st_math.h"

START_TEST(abs1) {
  int value = 0;
  ck_assert_int_eq(abs(value), st_abs(value));
}
END_TEST

START_TEST(abs2) {
  int value = 276447231;
  ck_assert_int_eq(abs(value), st_abs(value));
}
END_TEST

START_TEST(abs3) {
  int value = -276447231;
  ck_assert_int_eq(abs(value), st_abs(value));
}
END_TEST

START_TEST(fabs0) {
  double value = -0;
  ck_assert_ldouble_eq_tol(st_fabs(value), fabs(value), 1e-7);
}
END_TEST

START_TEST(fabs1) {
  double value = 0;
  ck_assert_ldouble_eq_tol(st_fabs(value), fabs(value), 1e-7);
}
END_TEST

START_TEST(fabs2) {
  double value = 1;
  ck_assert_ldouble_eq_tol(st_fabs(value), fabs(value), 1e-7);
}
END_TEST

START_TEST(fabs3) {
  double value = 12345678;
  ck_assert_ldouble_eq_tol(st_fabs(value), fabs(value), 1e-7);
}
END_TEST

START_TEST(fabs4) {
  double value = -65432100;
  ck_assert_ldouble_eq_tol(st_fabs(value), fabs(value), 1e-7);
}
END_TEST

START_TEST(fabs5) {
  double value = 0.12345678;
  ck_assert_ldouble_eq_tol(st_fabs(value), fabs(value), 1e-7);
}
END_TEST

START_TEST(fabs6) {
  double value = -0.65432100;
  ck_assert_ldouble_eq_tol(st_fabs(value), fabs(value), 1e-7);
}
END_TEST

START_TEST(fabs7) { ck_assert_double_nan(st_fabs(st_NAN)); }
END_TEST

START_TEST(fabs8) { ck_assert_double_infinite(st_fabs(st_INF)); }
END_TEST

START_TEST(fabs9) { ck_assert_double_infinite(st_fabs(-st_INF)); }
END_TEST

START_TEST(ceil1) {
  double a = 0;
  ck_assert_ldouble_eq_tol(st_ceil(a), ceil(a), 1e-7);
  double b = -0;
  ck_assert_ldouble_eq_tol(st_ceil(b), ceil(b), 1e-7);
}
END_TEST

START_TEST(ceil2) {
  double value = 0.00000001;
  ck_assert_ldouble_eq_tol(st_ceil(value), ceil(value), 1e-7);
}
END_TEST

START_TEST(ceil3) {
  double value = -0.00000001;
  ck_assert_ldouble_eq_tol(st_ceil(value), ceil(value), 1e-7);
}
END_TEST

START_TEST(ceil4) {
  double value = 0.99999999;
  ck_assert_ldouble_eq_tol(st_ceil(value), ceil(value), 1e-7);
}
END_TEST

START_TEST(ceil5) {
  double value = -0.99999999;
  ck_assert_ldouble_eq_tol(st_ceil(value), ceil(value), 1e-7);
}
END_TEST

START_TEST(ceil6) {
  double value = 33.12345678;
  ck_assert_ldouble_eq_tol(st_ceil(value), ceil(value), 1e-7);
}
END_TEST

START_TEST(ceil7) {
  double value = -64.65432100;
  ck_assert_ldouble_eq_tol(st_ceil(value), ceil(value), 1e-7);
}
END_TEST

START_TEST(ceil8) { ck_assert_double_nan(st_ceil(st_NAN)); }
END_TEST

START_TEST(ceil9) { ck_assert_double_infinite(st_ceil(st_INF)); }
END_TEST

START_TEST(ceil10) { ck_assert_double_infinite(st_ceil(-st_INF)); }
END_TEST

START_TEST(floor1) {
  double a = 0;
  ck_assert_ldouble_eq_tol(st_floor(a), floor(a), 1e-7);
  double b = -0;
  ck_assert_ldouble_eq_tol(st_floor(b), floor(b), 1e-7);
}
END_TEST

START_TEST(floor2) {
  double value = 0.00000001;
  ck_assert_ldouble_eq_tol(st_floor(value), floor(value), 1e-7);
}
END_TEST

START_TEST(floor3) {
  double value = -0.00000001;
  ck_assert_ldouble_eq_tol(st_floor(value), floor(value), 1e-7);
}
END_TEST

START_TEST(floor4) {
  double value = 0.99999999;
  ck_assert_ldouble_eq_tol(st_floor(value), floor(value), 1e-7);
}
END_TEST

START_TEST(floor5) {
  double value = -0.99999999;
  ck_assert_ldouble_eq_tol(st_floor(value), floor(value), 1e-7);
}
END_TEST

START_TEST(floor6) {
  double value = 33.12345678;
  ck_assert_ldouble_eq_tol(st_floor(value), floor(value), 1e-7);
}
END_TEST

START_TEST(floor7) {
  double value = -64.65432100;
  ck_assert_ldouble_eq_tol(st_floor(value), floor(value), 1e-7);
}
END_TEST

START_TEST(floor8) { ck_assert_double_infinite(st_floor(st_INF)); }
END_TEST

START_TEST(floor9) { ck_assert_double_nan(st_floor(st_NAN)); }
END_TEST

START_TEST(floor10) { ck_assert_double_infinite(st_floor(-st_INF)); }
END_TEST

START_TEST(sqrt0) {
  double value = -0;
  ck_assert_ldouble_eq_tol(st_sqrt(value), sqrt(value), 1e-7);
}
END_TEST

START_TEST(sqrt1) {
  double value = 0;
  ck_assert_ldouble_eq_tol(st_sqrt(value), sqrt(value), 1e-7);
}
END_TEST

START_TEST(sqrt2) {
  double value = 16.;
  ck_assert_ldouble_eq_tol(st_sqrt(value), sqrt(value), 1e-7);
}
END_TEST

START_TEST(sqrt3) {
  double value = 123456;
  ck_assert_ldouble_eq_tol(st_sqrt(value), sqrt(value), 1e-7);
}
END_TEST

START_TEST(sqrt4) {
  double value = 0.123456;
  ck_assert_ldouble_eq_tol(st_sqrt(value), sqrt(value), 1e-7);
}
END_TEST

START_TEST(sqrt5) {
  double value = 0.999999;
  ck_assert_ldouble_eq_tol(st_sqrt(value), sqrt(value), 1e-7);
}
END_TEST

START_TEST(sqrt6) {
  double value = -50;
  ck_assert_int_eq(st_sqrt(value) == NAN, sqrt(value) == NAN);
}
END_TEST

START_TEST(sqrt7) {
  for (double i = 0; i <= 1000; i++)
    ck_assert_ldouble_eq_tol(st_sqrt(i), sqrt(i), 1e-7);
}
END_TEST

START_TEST(sqrt8) { ck_assert_double_nan(st_sqrt(st_NAN)); }
END_TEST

START_TEST(sqrt9) { ck_assert_double_infinite(st_sqrt(st_INF)); }
END_TEST

START_TEST(sqrt10) {
  ck_assert_double_nan(sqrt(-st_INF));
  ck_assert_double_nan(st_sqrt(-st_INF));
}
END_TEST

START_TEST(exp_1) {
  double value = 0;
  ck_assert_ldouble_eq_tol(st_exp(value), exp(value), 1e-7);
}
END_TEST

START_TEST(exp_2) {
  double value = 1;
  ck_assert_ldouble_eq_tol(st_exp(value), exp(value), 1e-7);
}
END_TEST

START_TEST(exp_3) {
  double value = 0.123456;
  ck_assert_ldouble_eq_tol(st_exp(value), exp(value), 1e-7);
}
END_TEST

START_TEST(exp_4) {
  double value = -0.654321;
  ck_assert_ldouble_eq_tol(st_exp(value), exp(value), 1e-7);
}
END_TEST

START_TEST(exp_5) {
  double value = 0.999999;
  ck_assert_ldouble_eq_tol(st_exp(value), exp(value), 1e-7);
}
END_TEST

START_TEST(exp_6) {
  double value = 123456;
  ck_assert_ldouble_eq(st_exp(value), exp(value));
}
END_TEST

START_TEST(exp_7) {
  double value = -654321;
  ck_assert_ldouble_eq_tol(st_exp(value), exp(value), 1e-7);
}
END_TEST

START_TEST(exp_8) {
  for (double i = -10; i < 10; i++)
    ck_assert_ldouble_eq_tol(st_exp(i), exp(i), 1e-7);
}
END_TEST

START_TEST(exp_9) {
  double value = -st_INF;
  ck_assert_ldouble_eq_tol(st_exp(value), exp(value), 1e-7);
}
END_TEST

START_TEST(exp_10) {
  double value = st_INF;
  ck_assert_double_infinite(st_exp(value));
}
END_TEST

START_TEST(exp_11) {
  double value = st_NAN;
  ck_assert_ldouble_nan(st_exp(value));
}
END_TEST

START_TEST(fmod0) {
  ck_assert_ldouble_eq_tol(st_fmod(-0, 3.7), fmod(-0, 3.7), 1e-7);
}
END_TEST

START_TEST(fmod1) {
  ck_assert_ldouble_eq_tol(st_fmod(456.87678, 3.7), fmod(456.87678, 3.7), 1e-7);
}
END_TEST

START_TEST(fmod2) {
  ck_assert_ldouble_eq_tol(st_fmod(36677.546546, 4.1), fmod(36677.546546, 4.1),
                           1e-7);
}
END_TEST

START_TEST(fmod3) {
  ck_assert_ldouble_eq_tol(st_fmod(23.456, -4.355), fmod(23.456, -4.355), 1e-7);
}
END_TEST

START_TEST(fmod4) { ck_assert_ldouble_nan(st_fmod(0., 0.)); }
END_TEST

START_TEST(fmod5) {
  ck_assert_ldouble_eq_tol(st_fmod(0, 3.7), fmod(0, 3.7), 1e-7);
}
END_TEST

START_TEST(fmod6) { ck_assert_ldouble_nan(st_fmod(st_INF, st_NAN)); }
END_TEST

START_TEST(fmod7) {
  ck_assert_ldouble_eq_tol(st_fmod(36677.546546, st_INF),
                           fmod(36677.546546, st_INF), 1e-7);
}
END_TEST

START_TEST(fmod8) { ck_assert_ldouble_nan(st_fmod(4.5, st_NAN)); }
END_TEST

START_TEST(fmod9) { ck_assert_ldouble_nan(st_fmod(st_NAN, 4.5)); }
END_TEST

START_TEST(sin1) {
  double value = 0;
  ck_assert_ldouble_eq_tol(st_sin(value), sin(value), 1e-7);
}
END_TEST

START_TEST(sin2) {
  double value = 1.5;
  ck_assert_ldouble_eq_tol(st_sin(value), sin(value), 1e-7);
}
END_TEST

START_TEST(sin3) {
  double value = -2;
  ck_assert_ldouble_eq_tol(st_sin(value), sin(value), 1e-7);
}
END_TEST

START_TEST(sin4) {
  double value = -20;
  ck_assert_ldouble_eq_tol(st_sin(value), sin(value), 1e-7);
}
END_TEST

START_TEST(sin5) {
  double value = 20;
  ck_assert_ldouble_eq_tol(st_sin(value), sin(value), 1e-7);
}
END_TEST

START_TEST(sin6) { ck_assert_ldouble_nan(st_sin(st_NAN)); }
END_TEST

START_TEST(sin7) { ck_assert_ldouble_nan(st_sin(st_INF)); }
END_TEST

START_TEST(sin8) { ck_assert_ldouble_nan(st_sin(-st_INF)); }
END_TEST

START_TEST(cos1) {
  double value = 0;
  ck_assert_ldouble_eq_tol(st_cos(value), cos(value), 1e-7);
}
END_TEST

START_TEST(cos2) {
  double value = -20;
  ck_assert_ldouble_eq_tol(st_cos(value), cos(value), 1e-7);
}
END_TEST

START_TEST(cos3) {
  double value = 20;
  ck_assert_ldouble_eq_tol(st_cos(value), cos(value), 1e-7);
}
END_TEST

START_TEST(cos4) { ck_assert_ldouble_nan(st_cos(st_INF)); }
END_TEST

START_TEST(cos5) { ck_assert_ldouble_nan(st_cos(-st_INF)); }
END_TEST

START_TEST(cos6) {
  double value = 1.432;
  ck_assert_ldouble_eq_tol(st_cos(value), cos(value), 1e-7);
}
END_TEST

START_TEST(cos7) { ck_assert_ldouble_nan(st_cos(st_NAN)); }
END_TEST

START_TEST(tan1) {
  double value = 0;
  ck_assert_ldouble_eq_tol(st_tan(value), tan(value), 1e-7);
}
END_TEST

START_TEST(tan2) {
  double value = 1.534;
  ck_assert_ldouble_eq_tol(st_tan(value), tan(value), 1e-7);
}
END_TEST

START_TEST(tan3) { ck_assert_ldouble_nan(st_tan(st_NAN)); }
END_TEST

START_TEST(tan4) { ck_assert_ldouble_nan(st_tan(st_INF)); }
END_TEST

START_TEST(tan5) { ck_assert_ldouble_nan(st_tan(-st_INF)); }
END_TEST

START_TEST(tan6) {
  double value = -1.534;
  ck_assert_ldouble_eq_tol(st_tan(value), tan(value), 1e-7);
}
END_TEST

START_TEST(tan7) {
  double value = -20;
  ck_assert_ldouble_eq_tol(st_tan(value), tan(value), 1e-7);
}
END_TEST

START_TEST(tan8) {
  double value = 20;
  ck_assert_ldouble_eq_tol(st_tan(value), tan(value), 1e-7);
}
END_TEST

START_TEST(atan1) {
  double value = 0;
  ck_assert_ldouble_eq_tol(st_atan(value), atan(value), 1e-7);
}
END_TEST

START_TEST(atan3) {
  double value = 1.5;
  ck_assert_double_eq_tol(st_atan(value), atan(value), 1e-7);
}
END_TEST

START_TEST(atan4) {
  double value = -20;
  ck_assert_double_eq_tol(st_atan(value), atan(value), 1e-7);
}
END_TEST

START_TEST(atan5) {
  double value = 20;
  ck_assert_double_eq_tol(st_atan(value), atan(value), 1e-7);
}
END_TEST

START_TEST(atan6) {
  double value = st_INF;
  ck_assert_double_eq_tol(st_atan(value), atan(value), 1e-7);
}
END_TEST

START_TEST(atan7) {
  double value = -st_INF;
  ck_assert_double_eq_tol(st_atan(value), atan(value), 1e-7);
}
END_TEST

START_TEST(atan8) { ck_assert_ldouble_nan(st_atan(st_NAN)); }
END_TEST

START_TEST(atan9) {
  double value = -1.5;
  ck_assert_double_eq_tol(st_atan(value), atan(value), 1e-7);
}
END_TEST

START_TEST(asin1) {
  double value = 0;
  ck_assert_ldouble_eq_tol(st_asin(value), asin(value), 1e-7);
}
END_TEST

START_TEST(asin3) {
  double value = 0.5123;
  ck_assert_ldouble_eq_tol(st_asin(value), asin(value), 1e-7);
}
END_TEST

START_TEST(asin4) {
  double value = -0.5123;
  ck_assert_ldouble_eq_tol(st_asin(value), asin(value), 1e-7);
}
END_TEST

START_TEST(asin5) {
  double value = 1;
  ck_assert_ldouble_eq_tol(st_asin(value), asin(value), 1e-7);
}
END_TEST

START_TEST(asin6) {
  double value = -1;
  ck_assert_ldouble_eq_tol(st_asin(value), asin(value), 1e-7);
}
END_TEST

START_TEST(asin7) {
  double value = 20;
  ck_assert_ldouble_nan(st_asin(value));
}
END_TEST

START_TEST(asin8) {
  double value = -20;
  ck_assert_ldouble_nan(st_asin(value));
}
END_TEST

START_TEST(asin9) {
  double value = st_NAN;
  ck_assert_ldouble_nan(st_asin(value));
}
END_TEST

START_TEST(acos1) {
  double value = 0;
  ck_assert_ldouble_eq_tol(st_acos(value), acos(value), 1e-7);
}
END_TEST

START_TEST(acos2) {
  double value = 1;
  ck_assert_ldouble_eq_tol(st_acos(value), acos(value), 1e-7);
}
END_TEST

START_TEST(acos3) {
  double value = -1;
  ck_assert_ldouble_eq_tol(st_acos(value), acos(value), 1e-7);
}
END_TEST

START_TEST(acos4) {
  double value = 20;
  ck_assert_ldouble_nan(st_acos(value));
}
END_TEST

START_TEST(acos5) {
  double value = -20;
  ck_assert_ldouble_nan(st_acos(value));
}
END_TEST

START_TEST(acos6) { ck_assert_ldouble_nan(st_acos(st_NAN)); }
END_TEST

START_TEST(log1) {
  double value = 0;
  ck_assert_double_infinite(st_log(value));
}
END_TEST

START_TEST(log_2) {
  double value = 1;
  ck_assert_ldouble_eq_tol(st_log(value), log(value), 1e-7);
}
END_TEST

START_TEST(log3) {
  double value = 0.123456;
  ck_assert_ldouble_eq_tol(st_exp(value), exp(value), 1e-7);
}
END_TEST

START_TEST(log4) {
  double value = -0.654321;
  ck_assert_ldouble_nan(st_log(value));
}
END_TEST

START_TEST(log5) {
  double value = 0.999999;
  ck_assert_ldouble_eq_tol(st_log(value), log(value), 1e-7);
}
END_TEST

START_TEST(log6) {
  double value = 123456;
  ck_assert_ldouble_eq_tol(st_log(value), log(value), 1e-7);
}
END_TEST

START_TEST(log7) {
  double value = -654321;
  ck_assert_ldouble_nan(st_log(value));
}
END_TEST

START_TEST(log8) {
  double value = -st_INF;
  ck_assert_ldouble_nan(st_log(value));
}
END_TEST

START_TEST(log9) {
  double value = st_INF;
  ck_assert_double_infinite(st_log(value));
}
END_TEST

START_TEST(log_10) {
  double value = st_NAN;
  ck_assert_ldouble_nan(st_log(value));
}
END_TEST

START_TEST(pow1) {
  double base = 0;
  double exp = -3;
  ck_assert_double_infinite(st_pow(base, exp));
}
END_TEST

START_TEST(pow2) {
  double base = 0;
  double exp = -st_INF;
  ck_assert_double_infinite(st_pow(base, exp));
}
END_TEST

START_TEST(pow3) {
  double base = 0;
  double exp = 1.345;
  ck_assert_ldouble_eq_tol(st_pow(base, exp), pow(base, exp), 1e-7);
}
END_TEST

START_TEST(pow4) {
  double base = 0;
  double exp = 1.345;
  ck_assert_ldouble_eq_tol(st_pow(base, exp), pow(base, exp), 1e-7);
}
END_TEST

START_TEST(pow5) {
  double base = -1;
  double exp = st_INF;
  ck_assert_ldouble_eq_tol(st_pow(base, exp), pow(base, exp), 1e-7);
}
END_TEST

START_TEST(pow6) {
  double base = 1;
  double exp = 123;
  ck_assert_ldouble_eq_tol(st_pow(base, exp), pow(base, exp), 1e-7);
}
END_TEST

START_TEST(pow7) {
  double base = 1;
  double exp = st_NAN;
  ck_assert_ldouble_eq_tol(st_pow(base, exp), pow(base, exp), 1e-7);
}
END_TEST

START_TEST(pow8) {
  double base = st_NAN;
  double exp = 0;
  ck_assert_ldouble_eq_tol(st_pow(base, exp), pow(base, exp), 1e-7);
}
END_TEST

START_TEST(pow9) {
  double base = -254;
  double exp = 0;
  ck_assert_ldouble_eq_tol(st_pow(base, exp), pow(base, exp), 1e-7);
}
END_TEST

START_TEST(pow10) {
  double base = -254;
  double exp = 1.345;
  ck_assert_ldouble_nan(st_pow(base, exp));
}
END_TEST

START_TEST(pow11) {
  double base = 0.5;
  double exp = -st_INF;
  ck_assert_double_infinite(st_pow(base, exp));
}
END_TEST

START_TEST(pow12) {
  double base = -0.45;
  double exp = -st_INF;
  ck_assert_double_infinite(st_pow(base, exp));
}
END_TEST

START_TEST(pow13) {
  double base = -1234.5;
  double exp = -st_INF;
  ck_assert_ldouble_eq_tol(st_pow(base, exp), pow(base, exp), 1e-7);
}
END_TEST

START_TEST(pow14) {
  double base = 1234.5;
  double exp = -st_INF;
  ck_assert_ldouble_eq_tol(st_pow(base, exp), pow(base, exp), 1e-7);
}
END_TEST

START_TEST(pow15) {
  double base = 0.5;
  double exp = -st_INF;
  ck_assert_double_infinite(st_pow(base, exp));
}
END_TEST

START_TEST(pow16) {
  double base = -0.45;
  double exp = -st_INF;
  ck_assert_double_infinite(st_pow(base, exp));
}
END_TEST

START_TEST(pow17) {
  double base = -1234.5;
  double exp = -st_INF;
  ck_assert_ldouble_eq_tol(st_pow(base, exp), pow(base, exp), 1e-7);
}
END_TEST

START_TEST(pow18) {
  double base = 1234.5;
  double exp = -st_INF;
  ck_assert_ldouble_eq_tol(st_pow(base, exp), pow(base, exp), 1e-7);
}
END_TEST

START_TEST(pow19) {
  double base = -st_INF;
  double exp = -23.43;
  ck_assert_ldouble_eq_tol(st_pow(base, exp), pow(base, exp), 1e-7);
}
END_TEST

START_TEST(pow20) {
  double base = -st_INF;
  double exp = -2;
  ck_assert_ldouble_eq_tol(st_pow(base, exp), pow(base, exp), 1e-7);
}
END_TEST

START_TEST(pow21) {
  double base = -st_INF;
  double exp = 123;
  ck_assert_double_infinite(st_pow(base, exp));
}
END_TEST

START_TEST(pow22) {
  double base = -st_INF;
  double exp = 123.345;
  ck_assert_double_infinite(st_pow(base, exp));
}
END_TEST

START_TEST(pow23) {
  double base = st_INF;
  double exp = 12;
  ck_assert_double_infinite(st_pow(base, exp));
}
END_TEST

START_TEST(pow24) {
  double base = st_INF;
  double exp = 12;
  ck_assert_double_infinite(st_pow(base, exp));
}
END_TEST

START_TEST(pow25) {
  double base = st_NAN;
  double exp = 12;
  ck_assert_ldouble_nan(st_pow(base, exp));
}
END_TEST

START_TEST(pow26) {
  double base = 21;
  double exp = st_NAN;
  ck_assert_ldouble_nan(st_pow(base, exp));
}
END_TEST

START_TEST(pow27) {
  double base = st_NAN;
  double exp = st_NAN;
  ck_assert_ldouble_nan(st_pow(base, exp));
}
END_TEST

START_TEST(pow28) {
  double base = -1;
  double exp = -st_NAN;
  ck_assert_ldouble_nan(st_pow(base, exp));
}
END_TEST

START_TEST(pow29) {
  double base = 0.5;
  double exp = st_INF;
  ck_assert_ldouble_eq_tol(st_pow(base, exp), pow(base, exp), 1e-7);
}
END_TEST

START_TEST(pow30) {
  double base = 123;
  double exp = st_INF;
  ck_assert_double_infinite(st_pow(base, exp));
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, abs1);
  tcase_add_test(tc1_1, abs2);
  tcase_add_test(tc1_1, abs3);
  tcase_add_test(tc1_1, fabs0);
  tcase_add_test(tc1_1, fabs1);
  tcase_add_test(tc1_1, fabs2);
  tcase_add_test(tc1_1, fabs3);
  tcase_add_test(tc1_1, fabs4);
  tcase_add_test(tc1_1, fabs5);
  tcase_add_test(tc1_1, fabs6);
  tcase_add_test(tc1_1, fabs7);
  tcase_add_test(tc1_1, fabs8);
  tcase_add_test(tc1_1, fabs9);
  tcase_add_test(tc1_1, ceil1);
  tcase_add_test(tc1_1, ceil2);
  tcase_add_test(tc1_1, ceil3);
  tcase_add_test(tc1_1, ceil4);
  tcase_add_test(tc1_1, ceil5);
  tcase_add_test(tc1_1, ceil6);
  tcase_add_test(tc1_1, ceil7);
  tcase_add_test(tc1_1, ceil8);
  tcase_add_test(tc1_1, ceil9);
  tcase_add_test(tc1_1, ceil10);
  tcase_add_test(tc1_1, floor1);
  tcase_add_test(tc1_1, floor2);
  tcase_add_test(tc1_1, floor3);
  tcase_add_test(tc1_1, floor4);
  tcase_add_test(tc1_1, floor5);
  tcase_add_test(tc1_1, floor6);
  tcase_add_test(tc1_1, floor7);
  tcase_add_test(tc1_1, floor8);
  tcase_add_test(tc1_1, floor9);
  tcase_add_test(tc1_1, floor10);
  tcase_add_test(tc1_1, sqrt0);
  tcase_add_test(tc1_1, sqrt1);
  tcase_add_test(tc1_1, sqrt2);
  tcase_add_test(tc1_1, sqrt3);
  tcase_add_test(tc1_1, sqrt4);
  tcase_add_test(tc1_1, sqrt5);
  tcase_add_test(tc1_1, sqrt6);
  tcase_add_test(tc1_1, sqrt7);
  tcase_add_test(tc1_1, sqrt8);
  tcase_add_test(tc1_1, sqrt9);
  tcase_add_test(tc1_1, sqrt10);
  tcase_add_test(tc1_1, exp_1);
  tcase_add_test(tc1_1, exp_2);
  tcase_add_test(tc1_1, exp_3);
  tcase_add_test(tc1_1, exp_4);
  tcase_add_test(tc1_1, exp_5);
  tcase_add_test(tc1_1, exp_6);
  tcase_add_test(tc1_1, exp_7);
  tcase_add_test(tc1_1, exp_8);
  tcase_add_test(tc1_1, exp_9);
  tcase_add_test(tc1_1, exp_10);
  tcase_add_test(tc1_1, exp_11);
  tcase_add_test(tc1_1, fmod0);
  tcase_add_test(tc1_1, fmod1);
  tcase_add_test(tc1_1, fmod2);
  tcase_add_test(tc1_1, fmod3);
  tcase_add_test(tc1_1, fmod4);
  tcase_add_test(tc1_1, fmod5);
  tcase_add_test(tc1_1, fmod6);
  tcase_add_test(tc1_1, fmod7);
  tcase_add_test(tc1_1, fmod8);
  tcase_add_test(tc1_1, fmod9);
  tcase_add_test(tc1_1, sin1);
  tcase_add_test(tc1_1, sin2);
  tcase_add_test(tc1_1, sin3);
  tcase_add_test(tc1_1, sin4);
  tcase_add_test(tc1_1, sin5);
  tcase_add_test(tc1_1, sin6);
  tcase_add_test(tc1_1, sin7);
  tcase_add_test(tc1_1, sin8);
  tcase_add_test(tc1_1, cos1);
  tcase_add_test(tc1_1, cos2);
  tcase_add_test(tc1_1, cos3);
  tcase_add_test(tc1_1, cos4);
  tcase_add_test(tc1_1, cos5);
  tcase_add_test(tc1_1, cos6);
  tcase_add_test(tc1_1, cos7);
  tcase_add_test(tc1_1, tan1);
  tcase_add_test(tc1_1, tan2);
  tcase_add_test(tc1_1, tan3);
  tcase_add_test(tc1_1, tan4);
  tcase_add_test(tc1_1, tan5);
  tcase_add_test(tc1_1, tan6);
  tcase_add_test(tc1_1, tan7);
  tcase_add_test(tc1_1, tan8);
  tcase_add_test(tc1_1, atan1);
  tcase_add_test(tc1_1, atan3);
  tcase_add_test(tc1_1, atan4);
  tcase_add_test(tc1_1, atan5);
  tcase_add_test(tc1_1, atan6);
  tcase_add_test(tc1_1, atan7);
  tcase_add_test(tc1_1, atan8);
  tcase_add_test(tc1_1, atan9);
  tcase_add_test(tc1_1, asin1);
  tcase_add_test(tc1_1, asin3);
  tcase_add_test(tc1_1, asin4);
  tcase_add_test(tc1_1, asin5);
  tcase_add_test(tc1_1, asin6);
  tcase_add_test(tc1_1, asin7);
  tcase_add_test(tc1_1, asin8);
  tcase_add_test(tc1_1, asin9);
  tcase_add_test(tc1_1, acos1);
  tcase_add_test(tc1_1, acos2);
  tcase_add_test(tc1_1, acos3);
  tcase_add_test(tc1_1, acos4);
  tcase_add_test(tc1_1, acos5);
  tcase_add_test(tc1_1, acos6);
  tcase_add_test(tc1_1, log1);
  tcase_add_test(tc1_1, log_2);
  tcase_add_test(tc1_1, log3);
  tcase_add_test(tc1_1, log4);
  tcase_add_test(tc1_1, log5);
  tcase_add_test(tc1_1, log6);
  tcase_add_test(tc1_1, log7);
  tcase_add_test(tc1_1, log8);
  tcase_add_test(tc1_1, log9);
  tcase_add_test(tc1_1, log_10);
  tcase_add_test(tc1_1, pow1);
  tcase_add_test(tc1_1, pow2);
  tcase_add_test(tc1_1, pow3);
  tcase_add_test(tc1_1, pow4);
  tcase_add_test(tc1_1, pow5);
  tcase_add_test(tc1_1, pow6);
  tcase_add_test(tc1_1, pow7);
  tcase_add_test(tc1_1, pow8);
  tcase_add_test(tc1_1, pow9);
  tcase_add_test(tc1_1, pow10);
  tcase_add_test(tc1_1, pow11);
  tcase_add_test(tc1_1, pow12);
  tcase_add_test(tc1_1, pow13);
  tcase_add_test(tc1_1, pow14);
  tcase_add_test(tc1_1, pow15);
  tcase_add_test(tc1_1, pow16);
  tcase_add_test(tc1_1, pow17);
  tcase_add_test(tc1_1, pow18);
  tcase_add_test(tc1_1, pow19);
  tcase_add_test(tc1_1, pow20);
  tcase_add_test(tc1_1, pow21);
  tcase_add_test(tc1_1, pow22);
  tcase_add_test(tc1_1, pow23);
  tcase_add_test(tc1_1, pow24);
  tcase_add_test(tc1_1, pow25);
  tcase_add_test(tc1_1, pow26);
  tcase_add_test(tc1_1, pow27);
  tcase_add_test(tc1_1, pow28);
  tcase_add_test(tc1_1, pow29);
  tcase_add_test(tc1_1, pow30);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
